<% $LOAD_PATH << File.expand_path(File.join(File.dirname(__FILE__), 'lib')) %>
<% require 'config_helper' %>
<% include ConfigHelper %>

newrelic:
  license_key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>
  verbose: 1

  agents:
    <% agents do |agent| %>
      <%= agent.color %>:
        host: <%= agent.host %>
        port: <%= agent.port %>
        user: <%= agent.user %>
        password: <%= agent.password %>
        dbname: <%= agent.name %>
        sslmode: 'require'
  <% end %>