# Please make sure to update the license_key information with the license key for your New Relic
# account.
#
#
newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  # verbose: 1
#
# Agent Configuration:
#

<%
  require 'uri'
  uri = URI.parse(ENV['DATABASE_URL'])
%>

agents:
  # this is where configuration for agents belongs
  postgres:
    host: <%= uri.host %>
    port: <%= uri.port %>
    user: <%= uri.user %>
    password: <%= uri.password %>
    dbname: <%= uri.path.split('/')[1] %>
    sslmode: 'require'